// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFiTB-7gB9KFOJl7m9odEVhAxfoAMwYrM',
    appId: '1:24146060619:android:40a0fd734438b07649b4ce',
    messagingSenderId: '24146060619',
    projectId: 'campushub-86d4a',
    databaseURL: 'https://campushub-86d4a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campushub-86d4a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJQfi4y43lY-0nAh7oUbUQkV5bk2Sgy1Y',
    appId: '1:24146060619:web:35b516eb901894b949b4ce',
    messagingSenderId: '24146060619',
    projectId: 'campushub-86d4a',
    authDomain: 'campushub-86d4a.firebaseapp.com',
    databaseURL: 'https://campushub-86d4a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campushub-86d4a.firebasestorage.app',
  );

}